- hosts: all
  tasks:
# https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/
    # add renderaccount
    - name: Add Renderaccount
      user:
        name: "{{ renderaccount }}"
        groups: sudo
    - name: Install General Dependencies
      package:
        name: "libboost-all-dev, git, tar, unzip, wget, bzip2, build-essential, autoconf, libtool, libxml2-dev, libgeos-dev, libgeos++-dev, libpq-dev, libbz2-dev, libproj-dev, munin-node, munin, protobuf-c-compiler, libfreetype6-dev, libtiff5-dev, libicu-dev, libgdal-dev, libcairo2-dev, libcairomm-1.0-dev, apache2, apache2-dev, libagg-dev, liblua5.2-dev, ttf-unifont, lua5.1, liblua5.1-0-dev"

    - name: Install Postgres Database
      package:
        name: "postgresql, postgresql-contrib, postgis, postgresql-12-postgis-3, postgresql-12-postgis-3-scripts"
    - name: create data dir for postgresql
      file:
        path: "{{ postgresql_data_dir }}"
        state: directory
        owner: postgres
        group: postgres
    - name: template postgresql 12 config
      register: postgresql_conf
      template:
        src: postgresql.conf.12.j2
        dest: /etc/postgresql/12/main/postgresql.conf 
    - name: initilaize Database Directory
      when: postgresql_conf.changed
      shell: sudo -u postgres /usr/lib/postgresql/12/bin/initdb -D "{{ postgresql_data_dir }}"
    - name: restart postgresql
      when: postgresql_conf.changed
      systemd:
        name: postgresql
        state: restarted 
# TODO: Create database user
# createuser renderaccount # answer yes for superuser (although this isn't strictly necessary)
# createdb -E UTF8 -O renderaccount gis
    
#psql
#(that’ll put you at a “postgres=#” prompt)

#\c gis
#(it’ll answer “You are now connected to database ‘gis’ as user ‘postgres’”.)

# CREATE EXTENSION postgis;
# (it’ll answer CREATE EXTENSION)

# CREATE EXTENSION hstore;
# (it’ll answer CREATE EXTENSION)

# ALTER TABLE geometry_columns OWNER TO renderaccount;
# (it’ll answer ALTER TABLE)

# ALTER TABLE spatial_ref_sys OWNER TO renderaccount;
# (it’ll answer ALTER TABLE)

# \q
# (it’ll exit psql and go back to a normal Linux prompt)

# exit

    - name: Install osm2pgsql
      package:
        name: osm2pgsql

    - name: Install mapnik
      package:
        name: "autoconf, apache2-dev, libtool, libxml2-dev, libbz2-dev, libgeos-dev, libgeos++-dev, libproj-dev, gdal-bin, libmapnik-dev, mapnik-utils, python3-mapnik, python3-psycopg2, python3-yaml"

    - name: create build dir
      file:
        path: "{{ build_dir }}"
        state: directory

    - name: checkout switch2osm
      register: checkout_switch2osm
      ansible.builtin.git:
        repo: 'https://github.com/SomeoneElseOSM/mod_tile.git'
        dest: "{{ build_dir }}/mod_tile"
        update: no
        version: 'switch2osm'
    
    - name: build switch2osm
      when: checkout_switch2osm.changed
      shell: |
        cd "{{ build_dir }}"/mod_tile && ./autogen.sh && ./configure && make -j "{{ ansible_processor_vcpus }}" && make install && make install-mod_tile && ldconfig


    - name: checkout openstreetmap-carto
      register: checkout_carto
      ansible.builtin.git:
        repo: 'https://github.com/gravitystorm/openstreetmap-carto'
        dest: "{{ build_dir }}/openstreetmap-carto"
        update: no

    - name: install npm
      package:
        name: npm

    - name: install carto via npm
      shell: npm install --yes -g carto 

    - name: create mapnik.xml
      when: checkout_carto.changed
      shell: cd "{{ build_dir }}"/openstreetmap-carto && carto project.mml > mapnik.xml

    - name: create datadir
      file:
        path: "{{ data_dir }}"
        state: directory

    - name: Download Openstreetmap files
      get_url:
        url: https://download.geofabrik.de/europe/germany-latest.osm.pbf
        tmp_dest: "{{ data_dir }}"
        dest: "{{ data_dir }}/germany-latest.osm.pbf"
        mode: "0644"
        
        

   # import to database:
    - name: import to postgres
      shell: sudo -u postgres osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /data/tmp/src/openstreetmap-carto/openstreetmap-carto.lua -C 2500 --number-processes 4 -S /data/tmp/src/openstreetmap-carto/openstreetmap-carto.style /data/tmp/data/germany-latest.osm.pbf 


    - name: Create indexes in postgres
      shell: sudo -i postgres psql -d gis -f "{{ data_dir }}"/germany-latest/indexes.sql

    - name: shapefile download, create extra data dir underneath this dir
      shell: ./"{{ data_dir }}"/germany-latest/scripts/get-external-data.py

    - name: Carto Fonts
      shell: ./"{{ data_dir }}"/germany-latest/scripts/get-fonts.sh

    - name: template renderd.conf
      template:
        src: renderd.conf.j2
        dest: /usr/local/etc/renderd.conf

#The config file for “renderd” is “/usr/local/etc/renderd.conf”. Edit that with a text editor such as nano:

          #sudo nano /usr/local/etc/renderd.conf
          #A couple of lines in here may need changing. In the “renderd” section:

          #num_threads=4
          #If you’ve only got 2Gb or so of memory you’ll want to reduce this to 2. The “ajt” section corresponds to a “named map style” called “ajt”. You can have more than one of these sections if you want, provided that the URI is different for each. The “XML” line will need changing to something like:

          #XML=/home/renderaccount/src/openstreetmap-carto/mapnik.xml
          #You’ll want to change “renderaccount” to whatever non-root username you used above.

          #URI=/hot/
  
    - name: create mod_tile dir and render dir
      file:
        path: /var/lib/mod_tile
        state: directory
        owner: "{{ renderaccount }}"
        group: "{{ renderaccount }}"
      with_items:
        - "{{ mod_tile_dir }}"
        - "{{ renderdir }}"
  

    - name: template mod_tile for apache
      register: mod_tile_conf
      template:
        src: mod_tile.conf.j2
        dest: /etc/apache2/conf-available/mod_tile.conf

    - name: enable mod_tile conf for apache
      when: mod_tile_conf.changed
      shell: a2enconf mod_tile

    - name: renderd config for apache
      template:
        src: 000-default.conf.j2
        dest: /etc/apache2/sites-available/000-default.conf


    - name: reload apache
      systemd: 
        name: apache2
        state: restarted


